#!/bin/sh
# Regenerate rtl/index.qip: every RTL file the core needs, in a stable order.
# Run from the repo root whenever a file is added or removed.
set -e
out=rtl/index.qip
{
echo "# =============================================================================="
echo "# Cloak & Dagger core RTL -- generated by tools/gen_qip.sh, do not edit"
echo "# =============================================================================="
echo 'set_global_assignment -name SEARCH_PATH [file join $::quartus(qip_path) ""]'
echo ""
echo "# the package first: every module imports it"
echo 'set_global_assignment -name SYSTEMVERILOG_FILE [file join $::quartus(qip_path) "cloak_pkg.sv"]'
for f in $(cd rtl && ls *.sv | grep -v '^cloak_pkg.sv$' | sort); do
    echo "set_global_assignment -name SYSTEMVERILOG_FILE [file join \$::quartus(qip_path) \"$f\"]"
done
echo ""
echo "# T65 6502 (mist-devel/T65), GHDL-converted -- Verilog-2005, not SystemVerilog"
echo 'set_global_assignment -name VERILOG_FILE [file join $::quartus(qip_path) "../modules/cpu-t65/gen/t65.v"]'
} > $out
echo "wrote $out ($(grep -c FILE $out) files)"
